import os
import sys
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

"""
Django settings for PahalFoundation project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-local-dev-key-change-this')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.onrender.com',
    '.vercel.app',
    os.environ.get('RENDER_EXTERNAL_HOSTNAME', ''),
]

# Remove empty strings from allowed hosts
ALLOWED_HOSTS = [h for h in ALLOWED_HOSTS if h]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://*.onrender.com',
    'https://*.vercel.app',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pahal',
    'content',
    'django_ckeditor_5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PahalFoundation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PahalFoundation.wsgi.application'


# ============================================================
# Database — SQLite (100% free, built into Python, no setup)
# ============================================================
import shutil

DB_PATH = BASE_DIR / 'db.sqlite3'
TMP_DB_PATH = Path('/tmp/db.sqlite3')

try:
    # Check if BASE_DIR is writable (local or standard server)
    if os.access(BASE_DIR, os.W_OK):
        ACTIVE_DB = DB_PATH
    else:
        # We are on a read-only filesystem (Vercel serverless)
        if DB_PATH.exists() and not TMP_DB_PATH.exists():
            shutil.copy2(DB_PATH, TMP_DB_PATH)
        ACTIVE_DB = TMP_DB_PATH
except Exception:
    ACTIVE_DB = TMP_DB_PATH

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ACTIVE_DB,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# ============================================================
# Static files (CSS, JavaScript, Images)
# ============================================================
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build', 'static')

# WhiteNoise: serve compressed static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True


# ============================================================
# Media files — Local filesystem (100% free, no cloud needed)
# Uploaded files (student/volunteer photos, thumbnails, etc.)
# are stored in the media/ folder inside the project.
# ============================================================
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STORAGES = {
    # Media files → local disk (free, unlimited by your disk space)
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    # Static files → WhiteNoise (free)
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================================
# Razorpay Payment Gateway
# Use test keys (free) from https://dashboard.razorpay.com/
# Test mode: no real money is charged
# ============================================================
RAZORPAY_API_KEY = os.environ.get('RAZORPAY_API_KEY', '')
RAZORPAY_API_SECRET = os.environ.get('RAZORPAY_API_SECRET', '')


# CKEditor 5 config
try:
    from .ckeditorconfig import CKEDITOR_5_CONFIGS, CKEDITOR_5_FILE_UPLOAD_PERMISSION
except ImportError:
    CKEDITOR_5_CONFIGS = {}
    CKEDITOR_5_FILE_UPLOAD_PERMISSION = "authenticated"
